### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by chucker** [trenz-gmbh/trenz-docs#8]
A document should optionally be available in multiple languages. In this case, a file naming convention is used. For example, if a document is available in English and German, the following two files should exist:

    My-feature.en.md
    My-feature.de.md

## ToDo

How do we do per-language *titles*? A YAML header?

**Comment by ricardoboss** [comment]
What if wee do something like we did for authorization? Add a `.i18n`/`.lang` (or something other than that) in a folder which specifies which files have which title in what language, what the default/fallback language should be and maybe even which languages to show in the first place.

```toml
fallback = "en"
visible = ["en", "de"]

[en]
foo = "How to calculate Foo"

[de]
foo = "Wie man Foo berechnet"

[fr]
foo = "WIP"
```
